ID du contact;Civilité;Nom du compte;Prénom;Nom;Rue;Ville;Région/Province;Code postal;Pays;Téléphone;Téléphone mobile;Télécopie;Adresse e-mail;Propriétaire du compte
003D000001HT8uL;Mme;Moskito Productions;Yasmine;Schmit-Banzer;20 rue des Sangliers;Steinsel;;L-7344;LU;+352 26 33 44 82;;+352 27 88 88 81;yschmit@moskito.lu;Francis Gasparotto
003D000001HT96H;Mr;Mikado;Patrick;Bertrand;38 rue d'Esch;Luxembourg;;L-1470;LU;+352 45 75 45 1;;+352 45 75 45 75;pbertrand@mikado.lu;Francis Gasparotto
003D000001HT9lZ;Mr;IP Luxembourg;Henrique;Abreu;45 boulevard Pierre Frieden;Luxembourg;;L-1543;LU;+352 44 70 70 46 83;+352 661 70 46 83;+352 44 20 24;habreu@ipl.lu;Brice De Bruyne
003D000001HT9oN;Mr;Lola Communication;Filippe;Oliveira;5 ZI Grasbusch;Leudelange;;L-3370;LU;+352 26 48 59 34;;+352 26 48 59 40;foliveira@lola.lu;Brice De Bruyne
003D000001HTQ0z;Mme;H2a;Claire;Dewasmes;4 boulevard Grande Duchesse Charlotte;Luxembourg;;L-1330;LU;+352 26 36 64 1;;+352 26 36 64 50;dewasmes@h2a.lu;Francis Gasparotto
